### ISSUE TITLE
tut-plugin is removed from remote repo. Need to update the project with alternative

### ISSUE THREAD

**Issue by rajcspsg** [stanch/zipper#2]
Hi,

https://github.com/stanch/zipper/blob/master/project/plugins.sbt#L3 plugin is no more maintained and removed. 

Need to update to different library probably mdoc and build. 

@stanch please let me know your suggestions

**Comment by stanch** [comment]
I’ve never used mdoc, but from a quick glance it looks like it would fit the bill!

**Comment by stanch** [comment]
P.S. For reftree I would also look into replacing gitbook with docusaurus. I recall trying to update the docs a few years ago and bumping into some npm errors; besides gitbook CLI is deprecated from what I understand. I might take a stab at that some time this month.

**Comment by rajcspsg** [comment]
Hi @stanch How are you?
Sorry for late. I created website for zipper using docusaurus. Here is the link https://github.com/rajcspsg/zipper-docusaurus-demo

Here is the repo. Please have a look and let me know what you think.
Also please provide suggestions. I know the logo I created is kind of  weird :)

just clone the above repo and run `npm start` thats it

**Comment by rajcspsg** [comment]
@stanch did you get chance to look at sample docusaurus in the repo in mentioned above?

**Comment by rajcspsg** [comment]
@stanch wanted to followup again. did you get chance to check my new website design for zipper in the above mentioned repo?

**Comment by stanch** [comment]
Solved now with mdoc!
